In [1]:
using SymPy

In [2]:
@syms c d e

(c, d, e)

Definir una matriz 2x2

In [3]:
A= SymPy.Matrix([[c d];[1 -e]])

2×2 Matrix{Sym{PyCall.PyObject}}:
 c   d
 1  -e

In [ ]:
c=transpose(b)

2×1 transpose(::Matrix{Int64}) with eltype Int64:
 2
 0

In [32]:
B=[c d ; e 2d]

2×2 Matrix{Sym{PyCall.PyObject}}:
 c    d
 e  2*d

In [33]:
typeof(B)

Matrix{Sym{PyObject}} (alias for Array{Sym{PyCall.PyObject}, 2})

In [34]:
b=[2,0]

2-element Vector{Int64}:
 2
 0

In [37]:
solve(B, b)

Dict{Sym{PyCall.PyObject}, Sym{PyCall.PyObject}} with 1 entry:
  2 => 0

In [40]:
inv=B.inv()

2×2 Matrix{Sym{PyCall.PyObject}}:
      2/(2*c - e)     -1/(2*c - e)
 -e/(2*c*d - d*e)  c/(2*c*d - d*e)

In [41]:
solution= inv*b

2-element Vector{Sym{PyCall.PyObject}}:
        4/(2*c - e)
 -2*e/(2*c*d - d*e)

In [42]:
B*solution

2-element Vector{Sym{PyCall.PyObject}}:
  4*c/(2*c - e) - 2*d*e/(2*c*d - d*e)
 -4*d*e/(2*c*d - d*e) + 4*e/(2*c - e)

In [43]:
simplify(B*solution)

2-element Vector{Sym{PyCall.PyObject}}:
  4*c/(2*c - e) - 2*d*e/(2*c*d - d*e)
 -4*d*e/(2*c*d - d*e) + 4*e/(2*c - e)

In [44]:
B*inv

2×2 Matrix{Sym{PyCall.PyObject}}:
    2*c/(2*c - e) - d*e/(2*c*d - d*e)    c*d/(2*c*d - d*e) - c/(2*c - e)
 -2*d*e/(2*c*d - d*e) + 2*e/(2*c - e)  2*c*d/(2*c*d - d*e) - e/(2*c - e)

In [45]:
simplify(B*inv)

2×2 Matrix{Sym{PyCall.PyObject}}:
    2*c/(2*c - e) - d*e/(2*c*d - d*e)    c*d/(2*c*d - d*e) - c/(2*c - e)
 -2*d*e/(2*c*d - d*e) + 2*e/(2*c - e)  2*c*d/(2*c*d - d*e) - e/(2*c - e)

In [ ]:
simplify(inv*B)

2×2 Matrix{Sym{PyCall.PyObject}}:
 2*c/(2*c - e) - e/(2*c - e)                                        0
                           0  2*c*d/(2*c*d - d*e) - d*e/(2*c*d - d*e)

In [49]:
B.det()

2*c*d - d*e

In [60]:
solution

2-element Vector{Sym{PyCall.PyObject}}:
        4/(2*c - e)
 -2*e/(2*c*d - d*e)

In [63]:
solution[1]

   4   
-------
2*c - e

In [73]:
simplify(B.conjugate()*B)

2×2 Matrix{Sym{PyCall.PyObject}}:
   c*conjugate(c) + e*conjugate(d)  d*conjugate(c) + 2*d*conjugate(d)
 c*conjugate(e) + 2*e*conjugate(d)  4*d*conjugate(d) + d*conjugate(e)

In [74]:
using LinearAlgebra

In [83]:
R=Sym[c d ; -e d]

2×2 Matrix{Sym}:
  c  d
 -e  d

In [84]:
b1=Sym[1, 2]

2-element Vector{Sym}:
 1
 2

In [94]:
R.solve(b1)

2×1 Matrix{Sym{PyCall.PyObject}}:
            -1/(c + e)
 (2*c + e)/(c*d + d*e)

In [82]:
R.det()

0

In [86]:
inv=R.inv()

2×2 Matrix{Sym{PyCall.PyObject}}:
     1/(c + e)     -1/(c + e)
 e/(c*d + d*e)  c/(c*d + d*e)

In [89]:
simplify(inv*R)

2×2 Matrix{Sym{PyCall.PyObject}}:
 c/(c + e) + e/(c + e)                                  0
                     0  c*d/(c*d + d*e) + d*e/(c*d + d*e)

In [91]:
B.shape

(2, 2)

In [95]:
B.row(0)

1×2 Matrix{Sym{PyCall.PyObject}}:
 c  d

In [96]:
B.row(1)

1×2 Matrix{Sym{PyCall.PyObject}}:
 e  2*d

In [100]:
B.col(1)

2×1 Matrix{Sym{PyCall.PyObject}}:
   d
 2*d

In [101]:
B.col(-1)

2×1 Matrix{Sym{PyCall.PyObject}}:
   d
 2*d

In [102]:
M=sympy.ImmutableMatrix([c -2e; 1 d])

[c  -2*e]
[       ]
[1   d  ]

In [103]:
M.col_del(1)

[c]
[ ]
[1]

In [106]:
M.col_insert(1, Sym[-2e, d])

[c  -2*e  -2*e]
[             ]
[1   d     d  ]

In [107]:
M


[c  -2*e]
[       ]
[1   d  ]

In [108]:
M^-1

[    d         2*e   ]
[---------  ---------]
[c*d + 2*e  c*d + 2*e]
[                    ]
[   -1          c    ]
[---------  ---------]
[c*d + 2*e  c*d + 2*e]

In [111]:
simplify(M*M^-1)

[1  0]
[    ]
[0  1]

In [113]:
sympy.eye(3)

3×3 Matrix{Sym{PyCall.PyObject}}:
 1  0  0
 0  1  0
 0  0  1

In [114]:
sympy.zeros(2,3)

2×3 Matrix{Sym{PyCall.PyObject}}:
 0  0  0
 0  0  0

In [115]:
ones(2,3)

2×3 Matrix{Float64}:
 1.0  1.0  1.0
 1.0  1.0  1.0

In [116]:
ones(Sym, 2, 3)

2×3 Matrix{Sym}:
 1  1  1
 1  1  1

In [118]:
sympy.diag(1,2,3)

3×3 Matrix{Sym{PyCall.PyObject}}:
 1  0  0
 0  2  0
 0  0  3

In [121]:
sympy.diag(1, ones(Sym, 2, 2), Sym[2 3; 1 4])

5×5 Matrix{Sym{PyCall.PyObject}}:
 1  0  0  0  0
 0  1  1  0  0
 0  1  1  0  0
 0  0  0  2  3
 0  0  0  1  4

In [124]:
M

[c  -2*e]
[       ]
[1   d  ]

In [123]:
M.eigenvals()

Dict{Sym{PyCall.PyObject}, Sym{PyCall.PyObject}} with 2 entries:
  c/2 + d/2 + sqrt(c^2 - 2*c*d + d^2 - 8*e)/2 => 1
  c/2 + d/2 - sqrt(c^2 - 2*c*d + d^2 - 8*e)/2 => 1

In [127]:
M.eigenvects()

2-element Vector{Tuple{Sym{PyCall.PyObject}, Sym{PyCall.PyObject}, Vector{Sym{PyCall.PyObject}}}}:
 (c/2 + d/2 - sqrt(c^2 - 2*c*d + d^2 - 8*e)/2, 1, [Matrix([
[c/2 - d/2 - sqrt(c^2 - 2*c*d + d^2 - 8*e)/2],
[                                            1]])])
 (c/2 + d/2 + sqrt(c^2 - 2*c*d + d^2 - 8*e)/2, 1, [Matrix([
[c/2 - d/2 + sqrt(c^2 - 2*c*d + d^2 - 8*e)/2],
[                                            1]])])

In [132]:
eigvecs(B)

2×2 Matrix{Sym{PyCall.PyObject}}:
 -2*d/e + (c/2 + d - sqrt(c^2 - 4*c*d + 4*d^2 + 4*d*e)/2)/e  …  -2*d/e + (c/2 + d + sqrt(c^2 - 4*c*d + 4*d^2 + 4*d*e)/2)/e
                                                          1                                                              1

In [140]:
P, D=M.diagonalize()

(Matrix([
[c/2 - d/2 - sqrt(c^2 - 2*c*d + d^2 - 8*e)/2, c/2 - d/2 + sqrt(c^2 - 2*c*d + d^2 - 8*e)/2],
[                                            1,                                             1]]), Matrix([
[c/2 + d/2 - sqrt(c^2 - 2*c*d + d^2 - 8*e)/2,                                             0],
[                                            0, c/2 + d/2 + sqrt(c^2 - 2*c*d + d^2 - 8*e)/2]]))

In [141]:
P

[           _______________________             _______________________]
[          /  2            2                   /  2            2       ]
[c   d   \/  c  - 2*c*d + d  - 8*e   c   d   \/  c  - 2*c*d + d  - 8*e ]
[- - - - --------------------------  - - - + --------------------------]
[2   2               2               2   2               2             ]
[                                                                      ]
[                1                                   1                 ]

In [139]:
D

2×2 Matrix{Sym{PyCall.PyObject}}:
 c/2 + d - sqrt(c^2 - 4*c*d + 4*d^2 + 4*d*e)/2  …                                              0
                                             0     c/2 + d + sqrt(c^2 - 4*c*d + 4*d^2 + 4*d*e)/2

In [143]:
P*D*P^-1==M

true

In [144]:
lamda= symbols("lamda")
p=M.charpoly(lamda)
factor(p)

PurePoly(lamda^2 + (-c - d)*lamda + c*d + 2*e, lamda, domain='ZZ[c,d,e]')